piVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sample-app
spec:
  interval: 1m
  path: "./apps/sample-app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client

