apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sample-app
  namespace: flux-system
interval: 1m
path: "./clusters/kubernetes/apps/sample-app"
prune: true
sourceRef:
  kind: GitRepository
  name: flux-system
  namespace: flux-system
validation: client


